version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"